In [19]:
import pandas as pd
import numpy as np
import datetime
import os
from datetime import datetime
from collections import Counter
import sys

In [20]:
df_camp=pd.read_csv("Campaign3 database.csv")

df_camp['Start datetime']=pd.to_datetime(df_camp['Start datetime'])
df_camp['End datetime']=pd.to_datetime(df_camp['End datetime'])
df_camp.info()
df_camp

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Campaignid      18 non-null     int64
 1   CampaignName    18 non-null     object
 2   Start datetime  18 non-null     datetime64[ns]
 3   End datetime    18 non-null     datetime64[ns]
dtypes: datetime64[ns](2), int64(1), object(1)
memory usage: 704.0+ bytes

    Campaignid CampaignName      Start datetime        End datetime
0        12345       Camp_1 2022-11-21 10:00:00 2022-08-21 05:00:00
1        67890       Camp_2 2023-12-01 11:00:00 2023-07-27 06:00:00
2        23456       Camp_3 2023-03-23 12:00:00 2023-11-08 07:00:00
3        13567       Camp_4 2023-03-25 10:00:00 2023-05-15 05:00:00
4        23569       camp58 2023-04-23 10:00:00 2023-05-23 05:00:00
5       235644       camp44 2023-04-23 10:00:00 2023-05-26 05:00:00
6        23654       camp44 2023-12-05 10:00:00 2023-06-15 05:00:00
7        23564        camp8 2023-12-05 10:00:00 2023-06-13 05:00:00
8        25897        camp4 2023-08-15 10:00:00 2023-12-15 05:00:00
9       235689       camp58 2023-05-15 10:00:00 2023-06-17 05:00:00
10      652389       camp33 2023-04-23 10:00:00 2023-06-25 05:00:00
11     3625897      camp441 2023-06-28 10:00:00 2023-08-28 05:00:00
12     2365489       camp65 2023-04-23 10:00:00 2023-08-28 05:00:00
13       36524       camp65 2023-12-25 10:00:00 2024-12-23 05:00:00
14      369854       camp52 2023-04-25 10:00:00 2023-06-25 05:00:00
15      231456       camp22 2023-12-04 10:00:00 2023-12-05 05:00:00
16     3265489       camp33 2023-05-14 10:00:00 2023-06-15 05:00:00
17      326589       camp44 2023-06-15 10:00:00 2023-07-20 11:00:00

In [21]:
df_cand=pd.read_csv("Candidate1 database.csv")
df_cand.info()
df_cand

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Campaignid     18 non-null     int64
 1   Candidateid    18 non-null     int64
 2   CandidateName  18 non-null     object
 3   Party          18 non-null     object
 4   Symbol         18 non-null     object
 5   Gender         18 non-null     object
 6   vote_count     18 non-null     int64
 7   campaignid     18 non-null     int64
 8   candidateid    18 non-null     int64
dtypes: int64(5), object(4)
memory usage: 1.4+ KB

,Campaignid,Candidateid,CandidateName,Party,Symbol,Gender,vote_count,campaignid,candidateid
0,12345,123,Abhay,Congress,Palm,M,0,12345,123
1,12345,456,Hardeep,BJP,Lotus,M,0,12345,456
2,12345,789,Minakshi,AAP,Broom,F,0,12345,789
3,67890,121,Abhay,Congress,Palm,M,2,67890,121
4,67890,144,Hardeep,BJP,Lotus,M,0,67890,144
5,67890,169,Minakshi,AAP,Broom,F,0,67890,169
6,23456,196,Abhay,Congress,Palm,M,1,23456,196
7,23456,225,Hardeep,BJP,Lotus,M,0,23456,225
8,23456,256,Minakshi,AAP,Broom,F,0,23456,256
9,13567,289,Sakshi,BJP,Lotus,F,0,13567,289
10,13567,324,Akshat,AAP,Broom,M,0,13567,324
11,13567,361,Akshay,Congress,Palm,M,0,13567,361
12,23456,3215,Saloni,Congress,Palm,f,0,23456,3215
13,36524,3256,Aarav,Congress,Palm,M,0,36524,3256
14,13567,3654,Ahil,Congress,Palm,M,0,13567,3654
15,67890,2315,aarav,congress,palm,m,0,67890,2315
16,23456,32654,mkj,congress,palm,f,0,23456,32654
17,23456,135,anih,comgress,palm,male,0,23456,135

In [5]:
df_voter=pd.read_csv("voter1 database.csv")
df_voter

    Voterid     Name  Password  Gender  Voted_in_campaign
0      1234    Minal       1633      F              23456
1      5678     Aman       9425      M              23456
2      9012  Shubham       7898      M              23456
3      3456     Neha       5323      F              23456
4      7890   Rupali       1922      F              23456
5      2345    Amrit       7970      M              23456
6      6789    Vikas       3192      M              23456
7      1230   Prapti       7879      F              23456
8      1234    Minal       1633      F              13567
9      5678     Aman       9425      M              13567
10     9012  Shubham       7898      M              13567
11     3456     Neha       5323      F              13567
12     7890   Rupali       1922      F              13567
13     2345    Amrit       7970      M              13567
14     6789    Vikas       3192      M              13567
15     1230   Prapti       7879      F              13567

In [6]:
max_attempts=3

In [7]:
Datetime_format = "%Y-%m-%d %H:%M:%S"

In [8]:
def create_campaign():
    df_camp=pd.read_csv("Campaign3 database.csv")
    campaign_id = int(input("Enter campaign ID: "))
    
    if campaign_id in df_camp["Campaignid"].values:
        print("Campaign ID already exists.")
        create_campaign()
    else:
        campaign_name = input("Enter campaign name: ")
        start_date = input("Enter start date (YYYY-MM-DD HH:MM:SS): ")
        end_date = input("Enter end date (YYYY-MM-DD HH:MM:SS): ")
        df_camp.loc[len(df_camp)] = [campaign_id, campaign_name, start_date, end_date]
        df_camp.to_csv("Campaign3 database.csv", index=False)
        print("Campaign created successfully!")
        #print("please add candidate in camapaign ")
        #print(df_camp['Campaignid'].values)
        print("Which campaign would you like to add candidate?")
        print("Here is a list of campaign ids:",df_camp['Campaignid'].values)
        #campaignid=int(input("Enter campaign id"))
        
        add_candidate()

def add_candidate():
    #campaignid=int(input("Enter campaign id"))
    print("Please enter the following information when adding candidate")
    
    df_cand=pd.read_csv("Candidate1 database.csv")
    
    df_camp=pd.read_csv("Campaign3 database.csv")
    
    campaignid = int(input('Enter campaign ID: '))
    candidate_id = input('Enter candidate ID: ')
    candidate_name = input('Enter candidate name: ')
    
    party = input('Enter candidate party: ')
    symbol = input('Enter candidate symbol: ')
    gender = input('Enter candidate gender: ')
    
    Vote_count = 0
    camp_id = campaignid
    cand_id = candidate_id
    
    if campaignid not in df_camp['Campaignid'].values:
        print('Campaign not found.')
        add_candidate()
    
        
        
    
    
        #print('Campaign not found.')
    df_cand.loc[len(df_cand)] = [campaignid,candidate_id, candidate_name, party, symbol,gender,0,camp_id,cand_id]
    df_cand.to_csv('Candidate1 database.csv', index=False)
    print('Candidate added successfully.')
    print(df_cand)
    print("""press 1 for Admin login
    press 2 for voter login""")
    choice=int(input("Enter a number"))
    
    if choice== 1:
        admin_login()
    else:
        voter_login()

def publish_results():

    df_camp=pd.read_csv("Campaign3 database.csv")
    df_cand=pd.read_csv("Candidate1 database.csv")
    
    #print(df_cand)
    campaign_id = int(input("Enter campaign ID: "))
    #
    if campaign_id in df_cand['campaignid'].values:
        df_result = df_cand[df_cand['campaignid'] == campaign_id][['CandidateName', 'vote_count']]
        df_result = df_result.sort_values(by='vote_count', ascending=False)
        print(df_result)
        return
        
        
    else:
        print("Campaign ID does not exist. Please try again.")
        
def admin_login():
    max_attempts= 3
    for i in range(1,max_attempts+1):
   # attempts=0
    #while attempts<3:
    
    
        user_name = input("Enter your name:")
        pw = input("Enter your password")
        if user_name=="minal" and pw=="12345":
            print('Admin login successfully')
            
            admin_Homepage()
            break
        else:
            print((f'Incorrect username or password. {max_attempts - i} attempts remaining.'))
    else:
        print("Max login attempts reached. Exiting program.")
        
def admin_Homepage():
    print("Welcome minal")
    print("""1 . create campaign
    & add candidate
    2. publish result
    3. Exit""")
    choice =input("Enter the number::")

    if choice=="1":
        print("You can create campaign")
        return create_campaign()
    
    elif choice=="2":
        print("Declare result")
        return publish_results()
        

    else:
        print("Log out")
        
def voter_login():
    print("""" View live campaign
    View Candidate list in running campaign 
    Cast vote
    Exit""")
    df_voter=pd.read_csv("voter1 database.csv")
    attempts=3
    for i in range(1,attempts+1):
        voter_id = int(input("Enter voter id"))
        if voter_id in df_voter['Voterid'].values:
            print("You are a voter")
            live_campaigns()
            break
            
        
        else:
             print("you are not voter")
    else:
         print("Too many failed attempts,login failed...")
            
def live_campaigns():
    current_time = datetime.now()
    live_campaigns = df_camp[(df_camp["Start datetime"] <= current_time) & (df_camp["End datetime"] >= current_time)]
    if live_campaigns.empty:
        print("No live campaigns available for voting.")
        return None
    else:
        print("Live campaigns:") 
        for i, row in live_campaigns.iterrows():
            print(f"{i+1}. {row['CampaignName']} (ID: {row['Campaignid']})")
            
        
        cast_vote()
        
def cast_vote():
    voter_id=input("Please enter your voter ID again")
    df_camp=pd.read_csv("Campaign3 database.csv")
    df_cand=pd.read_csv("Candidate1 database.csv")
    df_voter=pd.read_csv("voter1 database.csv")

    df_cand.set_index(['Campaignid','Candidateid'],inplace=True)
    #print(df_cand)
    print("Which campaign do you want to vote in?")
    camp_id= int(input("Enter campaign id:"))
    cand_id= int(input("Enter candidate id for voting candidate"))
    df_cand.loc[(camp_id,cand_id),'vote_count']+=1
    
    print(df_cand)
        
    print("Your vote has been recorded")
    print("Successful Voting")
    #  df_cand.to_csv('Candidate1 database.csv', index=False)
    df_voter.to_csv('Voter1 database.csv', index=False)
            
    print(""""Do you want to vote again
        Press 1 for vote again
        press 2 for next voter
        press 3 for Admin login""")
    
    choice=input("Enter the number")
    if choice=='1':
        
        campaign_id2=int(input("Enter campaign id:"))
        if campaign_id2==camp_id:
                print("you can't cast vote in same campaign id")
        else:
            print("Which campaign do you want to vote in?")
            camp_id= int(input("Enter campaign id:"))
            cand_id= int(input("Enter candidate id for voting candidate"))
            df_cand.loc[(camp_id,cand_id),'vote_count']+=1
            df_cand.to_csv('Candidate1 database.csv', index=False)
            print(df_cand)
    elif choice=='2':
        print('1. View live campaign')
        print('2.View Candidate list in running campaign') 
        print('3. Cast vote')
        print('4. Exit')
        df_voter=pd.read_csv("voter1 database.csv")
        attempts=0
        while attempts<3:
            voter_id = int(input("Enter voter id"))
            if voter_id in df_voter['Voterid'].values:
                print("You are a voter")
                live_campaigns()
            
        
            else:
                print("you are not voter")
                attempts+=1
        print("Too many failed attempts,login failed...")
        
                
    else:
        admin_login()

In [9]:
def live_campaigns():
    current_time = datetime.now()
    live_campaigns = df_camp[(df_camp["Start datetime"] <= current_time) & (df_camp["End datetime"] >= current_time)]
    if live_campaigns.empty:
        print("No live campaigns available for voting.")
        return None
    else:
        print("Live campaigns:") 
        for i, row in live_campaigns.iterrows():
            print(f"{i+1}. {row['CampaignName']} (ID: {row['Campaignid']})")
            
        
        cast_vote()

In [10]:

def cast_vote():
    voter_id=input("Please enter your voter ID again")
    df_camp=pd.read_csv("Campaign3 database.csv")
    df_cand=pd.read_csv("Candidate1 database.csv")
    df_voter=pd.read_csv("voter1 database.csv")

    df_cand.set_index(['Campaignid','Candidateid'],inplace=True)
    #print(df_cand)
    print("Which campaign do you want to vote in?")
    camp_id= int(input("Enter campaign id:"))
    cand_id= int(input("Enter candidate id for voting candidate"))
    df_cand.loc[(camp_id,cand_id),'vote_count']+=1
    
    print(df_cand)
        
    print("Your vote has been recorded")
    print("Successful Voting")
    #  df_cand.to_csv('Candidate1 database.csv', index=False)
    df_voter.to_csv('Voter1 database.csv', index=False)
            
    print(""""Do you want to vote again
        Press 1 for vote again
        press 2 for next voter
        press 3 for Admin login""")
    
    choice=input("Enter the number")
    if choice=='1':
        
        campaign_id2=int(input("Enter campaign id:"))
        if campaign_id2==camp_id:
                print("you can't cast vote in same campaign id")
        else:
            print("Which campaign do you want to vote in?")
            camp_id= int(input("Enter campaign id:"))
            cand_id= int(input("Enter candidate id for voting candidate"))
            df_cand.loc[(camp_id,cand_id),'vote_count']+=1
            df_cand.to_csv('Candidate1 database.csv', index=False)
            print(df_cand)
    elif choice=='2':
        print('1. View live campaign')
        print('2.View Candidate list in running campaign') 
        print('3. Cast vote')
        print('4. Exit')
        df_voter=pd.read_csv("voter1 database.csv")
        attempts=0
        while attempts<3:
            voter_id = int(input("Enter voter id"))
            if voter_id in df_voter['Voterid'].values:
                print("You are a voter")
                live_campaigns()
            
        
            else:
                print("you are not voter")
                attempts+=1
        print("Too many failed attempts,login failed...")
        
                
    else:
        admin_login()

In [11]:
def publish_results():

    df_camp=pd.read_csv("Campaign3 database.csv")
    df_cand=pd.read_csv("Candidate1 database.csv")
    
    #print(df_cand)
    campaign_id = int(input("Enter campaign ID: "))
    #
    if campaign_id in df_cand['campaignid'].values:
        df_result = df_cand[df_cand['campaignid'] == campaign_id][['CandidateName', 'vote_count']]
        df_result = df_result.sort_values(by='vote_count', ascending=False)
        print(df_result)
        return
        
        
    else:
        print("Campaign ID does not exist. Please try again.")

In [12]:
def view_campaign():
    print("Campaign started")
    df_camp=pd.read_excel("Campaign database.xlsx")
    current_datetime = datetime.now()
    print(current_datetime)
    current_date = current_datetime.date()
    current_time = current_datetime.time()
    campaigns = df_camp[(df_camp['Start datetime'] <= str(current_datetime)) & (df_camp['End datetime'] >= str(current_datetime))]
    #campaigns = campaigns[(campaigns['start time'] <= str(current_time)) & (campaigns['End time'] >= str(current_time))]

    print("Live campaigns:")
    print(campaigns)
    #print(df_camp)
    #today = datetime.date.today()
    #now = datetime.datetime.now()

    #current_time = now.time()
    df=pd.DataFrame(df_camp,columns=['Campaignid','CampaignName','Start date','start time','End date','End time'])
    status=[]
    for i in df_camp.values:
        print(i)
        if i<current_datetime:
            status.append("Completed")
            
            
    else:
        status.append("Running")
    df['status']=status
    
    print("Now you can see completed and running campaigns")


    #print(df)
    print("Voter can cast vote in Running campaign")
    campaigns.to_csv("Campaign database.csv",index=False)
    
    df_5=pd.read_csv("Campaign database.csv",index=False)
    #print(df_5)
    running_campaigns=df_5[df_5['status']=="Running"]
    print("This is list of running campaigns")
    print(running_campaigns)
    df_cand=pd.read_excel("Candidate database.xlsx")
    running_campaign=df_cand[df_cand['Campaignid']==23456]
    
    campaign_id = int(input('Enter campaign ID: '))
    print("""This is the list of candidates in running campaign that
        voter can vote""")
    
    if campaign_id in df_camp['Campaignid'].values:
        candidates = df_cand[df_cand['Campaignid'] == campaign_id]
        
        print(candidates)

In [46]:
def e_voting():
    print("Welcome to the election portal")
    Choice=input("""Press 1 for Admin Login
    press 2 for Voter Login""")
    if Choice=="1":
        print("Welcome to the Admin portal")
        return admin_login()
    elif Choice=="2":
        print("Welcome to the Voter Portal")
        return voter_login()
    else:
        print("Invalid choice. Please try again.")
        return e_voting()

In [45]:
def admin_login():
    max_attempts= 3
    for i in range(1,max_attempts+1):
   # attempts=0
    #while attempts<3:
    
    
        user_name = input("Enter your name:")
        pw = input("Enter your password")
        if user_name=="minal" and pw=="12345":
            print('Admin login successfully')
            
            admin_Homepage()
            break
        else:
            print((f'Incorrect username or password. {max_attempts - i} attempts remaining.'))
    else:
        print("Max login attempts reached. Exiting program.")

In [13]:
def admin_Homepage():
    print("Welcome minal")
    print("""1 . create campaign
    & add candidate
    2. publish result
    3. Exit""")
    choice =input("Enter the number::")

    if choice=="1":
        print("You can create campaign")
        return create_campaign()
    
    elif choice=="2":
        print("Declare result")
        return publish_results()
        

    else:
        print("Log out")

In [14]:
def voter_login():
    print("""" View live campaign
    View Candidate list in running campaign 
    Cast vote
    Exit""")
    df_voter=pd.read_csv("voter1 database.csv")
    attempts=3
    for i in range(1,attempts+1):
        voter_id = int(input("Enter voter id"))
        if voter_id in df_voter['Voterid'].values:
            print("You are a voter")
            live_campaigns()
            break
            
        
        else:
             print("you are not voter")
    else:
         print("Too many failed attempts,login failed...")

In [22]:
def e_voting():
    print("Welcome to the election portal")
    while True:
        Choice = input("""Press 1 for Admin Login
Press 2 for Voter Login
Enter your choice: """)
        if Choice == "1":
            print("Welcome to the Admin portal")
            admin_login()
            break
        elif Choice == "2":
            print("Welcome to the Voter Portal")
            voter_login()
            break
        else:
            print("Invalid choice. Please try again.")

if __name__ == "__main__":
    e_voting()

Welcome to the election portal

Press 1 for Admin Login
Press 2 for Voter Login
Enter your choice:  1

Welcome to the Admin portal

Enter your name: minal
Enter your password 12345

Admin login successfully
Welcome minal
1 . create campaign
    & add candidate
    2. publish result
    3. Exit

Enter the number:: 1

You can create campaign

Enter campaign ID:  23564

Campaign ID already exists.

Enter campaign ID:  698756
Enter campaign name:  cam89
Enter start date (YYYY-MM-DD HH:MM:SS):  2023-05-19 10:00:00
Enter end date (YYYY-MM-DD HH:MM:SS):  2023-07-25 11:00:00

Campaign created successfully!
Which campaign would you like to add candidate?
Here is a list of campaign ids: [  12345   67890   23456   13567   23569  235644   23654   23564   25897
  235689  652389 3625897 2365489   36524  369854  231456 3265489  326589
  698756]
Please enter the following information when adding candidate

Enter campaign ID:  67890
Enter candidate ID:  235
Enter candidate name:  aniruddh
Enter candidate party:  congress
Enter candidate symbol:  palm
Enter candidate gender:  male

Candidate added successfully.
    Campaignid Candidateid CandidateName    Party  Symbol Gender  vote_count  \
0        12345         123         Abhay  Congress   Palm      M           0
1        12345         456       Hardeep       BJP  Lotus      M           0
2        12345         789      Minakshi       AAP  Broom      F           0
3        67890         121         Abhay  Congress   Palm      M           2
4        67890         144       Hardeep       BJP  Lotus      M           0
5        67890         169      Minakshi       AAP  Broom      F           0
6        23456         196         Abhay  Congress   Palm      M           1
7        23456         225       Hardeep       BJP  Lotus      M           0
8        23456         256      Minakshi       AAP  Broom      F           0
9        13567         289        Sakshi       BJP  Lotus      F           0
10       13567         324        Akshat       AAP  Broom      M           0
11       13567         361        Akshay  Congress   Palm      M           0
12       23456        3215        Saloni  Congress   Palm      f           0
13       36524        3256         Aarav  Congress   Palm      M           0
14       13567        3654          Ahil  Congress   Palm      M           0
15       67890        2315         aarav  congress   palm      m           0
16       23456       32654           mkj  congress   palm      f           0
17       23456         135          anih  comgress   palm   male           0
18       67890         235      aniruddh  congress   palm   male           0

    campaignid candidateid
0        12345         123
1        12345         456
2        12345         789
3        67890         121
4        67890         144
5        67890         169
6        23456         196
7        23456         225
8        23456         256
9        13567         289
10       13567         324
11       13567         361
12       23456        3215
13       36524        3256
14       13567        3654
15       67890        2315
16       23456       32654
17       23456         135
18       67890         235
press 1 for Admin login
    press 2 for voter login

Enter a number 2

" View live campaign
    View Candidate list in running campaign
    Cast vote
    Exit

Enter voter id 1234

You are a voter
Live campaigns:
3. Camp_3 (ID: 23456)
12. camp441 (ID: 3625897)
13. camp65 (ID: 2365489)

Please enter your voter ID again 23456

Which campaign do you want to vote in?

Enter campaign id: 23456
Enter candidate id for voting candidate 225

                       CandidateName    Party  Symbol Gender  vote_count  \
Campaignid Candidateid
12345      123                 Abhay  Congress   Palm      M           0
           456               Hardeep       BJP  Lotus      M           0
           789              Minakshi       AAP  Broom      F           0
67890      121                 Abhay  Congress   Palm      M           2
           144               Hardeep       BJP  Lotus      M           0
           169              Minakshi       AAP  Broom      F           0
23456      196                 Abhay  Congress   Palm      M           1
           225               Hardeep       BJP  Lotus      M           1
           256              Minakshi       AAP  Broom      F           0
13567      289                Sakshi       BJP  Lotus      F           0
           324                Akshat       AAP  Broom      M           0
           361                Akshay  Congress   Palm      M           0
23456      3215               Saloni  Congress   Palm      f           0
36524      3256                Aarav  Congress   Palm      M           0
13567      3654                 Ahil  Congress   Palm      M           0
67890      2315                aarav  congress   palm      m           0
23456      32654                 mkj  congress   palm      f           0
           135                  anih  comgress   palm   male           0
67890      235              aniruddh  congress   palm   male           0

                        campaignid  candidateid
Campaignid Candidateid
12345      123               12345          123
           456               12345          456
           789               12345          789
67890      121               67890          121
           144               67890          144
           169               67890          169
23456      196               23456          196
           225               23456          225
           256               23456          256
13567      289               13567          289
           324               13567          324
           361               13567          361
23456      3215              23456         3215
36524      3256              36524         3256
13567      3654              13567         3654
67890      2315              67890         2315
23456      32654             23456        32654
           135               23456          135
67890      235               67890          235
Your vote has been recorded
Successful Voting
"Do you want to vote again
        Press 1 for vote again
        press 2 for next voter
        press 3 for Admin login

Enter the number 3
Enter your name: minal
Enter your password 12345

Admin login successfully
Welcome minal
1 . create campaign
    & add candidate
    2. publish result
    3. Exit

Enter the number:: 2

Declare result

Enter campaign ID:  23456

   CandidateName  vote_count
6          Abhay           1
7        Hardeep           0
8       Minakshi           0
12        Saloni           0
16           mkj           0
17          anih           0

In [ ]:
def main():
    print("Enter Choice:")
    choice = int(input())
    if choice == 1:
        print()

In [ ]:
df_camp

In [ ]:
view_campaign()

In [ ]:
df_camp

In [ ]:
df_voter

In [4]:
df_cand

,Campaignid,Candidateid,CandidateName,Party,Symbol,Gender,vote_count,campaignid,candidateid
0,12345,123,Abhay,Congress,Palm,M,0,12345,123
1,12345,456,Hardeep,BJP,Lotus,M,0,12345,456
2,12345,789,Minakshi,AAP,Broom,F,0,12345,789
3,67890,121,Abhay,Congress,Palm,M,2,67890,121
4,67890,144,Hardeep,BJP,Lotus,M,0,67890,144
5,67890,169,Minakshi,AAP,Broom,F,0,67890,169
6,23456,196,Abhay,Congress,Palm,M,1,23456,196
7,23456,225,Hardeep,BJP,Lotus,M,0,23456,225
8,23456,256,Minakshi,AAP,Broom,F,0,23456,256
9,13567,289,Sakshi,BJP,Lotus,F,0,13567,289
10,13567,324,Akshat,AAP,Broom,M,0,13567,324
11,13567,361,Akshay,Congress,Palm,M,0,13567,361
12,23456,3215,Saloni,Congress,Palm,f,0,23456,3215
13,36524,3256,Aarav,Congress,Palm,M,0,36524,3256
14,13567,3654,Ahil,Congress,Palm,M,0,13567,3654
15,67890,2315,aarav,congress,palm,m,0,67890,2315